In [ ]:
# ----> Assignment(10) ----> Python_Filters_Practice

In [ ]:
# Task: Write a program

# Q> create and import below files

# 1. Create a friend_names.xls file  (atleast 10 names, columns are FriendName,Quality)
# Q1> create a dataframe which contains only your intelligent friends list.
# Q2> create a dataframe which contains only your funny friends list.


# 2. Create a family_members.xls file  (atleast 10 names, columns are FamilyMemberName*Relation)
# Q1> create a dataframe which contains only your brothers and sisters list.
# Q2> create a dataframe which contains only your parents list.
# Q3> create a dataframe which not contains your parents list.
# Q4> create a dataframe which not contains your brothers list.
# Q5> create a dataframe which contains either your brothers list or parents list.
# Q5> create a dataframe which contains your brothers list and parents list.


# 3. Create a Vegfood_items.xlsx file  (atleast 10 names, columns are VegFoodName*Taste)
# Q1>create a dataframe which are  soups items
# Q2>create a dataframe which are curry items
# Q3>create a dataframe which are fry items
# Q4>create a dataframe which contains soups and fry items
# Q5>create a dataframe which not contains soups and fry items
# Q6>create a dataframe which contains either soup or fry items



# 4. Create a NonVegfood_items.xlsx file  (atleast 10 names, columns are NonVegFoodName*Taste)
# Q1>create a dataframe which contains only chicken items
# Q2>create a dataframe which contains only mutton items
# Q3>create a dataframe which contains only Fry items
# Q4>create a dataframe which contains only Fry and chicken items
# Q5>create a dataframe which not contains Fry and chicken items
# Q6>create a dataframe which contains either Fry or mutton items

# 5. Create a month_names.xlsx file (atleast 12 names, columns are MonthName*Season)
# Q1>create a dataframe which contains only winter season months
# Q2>create a dataframe which contains only summer season months
# Q3>create a dataframe which contains only rainy season months
# Q4>create a dataframe which contains only winter and summer season months
# Q5>create a dataframe which not contains summer and rainy season months
# Q6>create a dataframe which contains either winter or rainy items


# 6. Create a flower_names.xlsx file  (atleast 12 names, columns are FlowercolourName_in_English^FlowercolourName_in_Hindi^FlowercolourName_in_Telugu)
# Q1>create a dataframe which contains only red colour flower list
# Q2>create a dataframe which contains only white colour flower list
# Q3>create a dataframe which contains only pink colour flower list
# Q4>create a dataframe which contains only red and pink colour list
# Q5>create a dataframe which not contains red and white colour list
# Q6>create a dataframe which contains either red or pink colour list

In [ ]:
# Q> create and import below files

# 1. Create a friend_names.xls file  (atleast 10 names, columns are FriendName,Quality)
# Q1> create a dataframe which contains only your intelligent friends list.
# Q2> create a dataframe which contains only your funny friends list.

In [ ]:
# 1. Create a friend_names.xls file  (atleast 10 names, columns are FriendName,Quality)

In [1]:
import pandas
import pandas as pd
df_fnames=pd.read_excel(r"C:\Users\hp\Downloads\friend_names.xlsx")
df_fnames

   S.No. Friend_Names      Quality
0      1        Salma       Active
1      2       Hamida  Intelligent
2      3      Jameela         Good
3      4      Shafika        Funny
4      5      Sultana         Best
5      6       Hanima  Intelligent
6      7        Munny     Innocent
7      8       Rehana        Funny
8      9         Asma  Intelligent
9     10       Vahida       Clever

In [ ]:
# ----> Only ['Intelligent'] ----> Use Symbol(==) 

Syntax:-
    
    a)  df1=df[df["Key"]=="Key_Value"]
        df1
    
                (or) 
        
    b)  df[df["Key"]=="Key_Value"]

In [2]:
# Q1> create a dataframe which contains only your intelligent friends list.

df1=df_fnames[df_fnames["Quality"]=="Intelligent"]
df1

   S.No. Friend_Names      Quality
1      2       Hamida  Intelligent
5      6       Hanima  Intelligent
8      9         Asma  Intelligent

In [ ]:
(or)

In [3]:
df_fnames[df_fnames["Quality"]=="Intelligent"]

   S.No. Friend_Names      Quality
1      2       Hamida  Intelligent
5      6       Hanima  Intelligent
8      9         Asma  Intelligent

In [ ]:
# Q2> create a dataframe which contains only your funny friends list.

In [ ]:
# ----> Only  ["Funny"]

In [4]:
df_fnames[df_fnames["Quality"]=="Funny"]

   S.No. Friend_Names Quality
3      4      Shafika   Funny
7      8       Rehana   Funny

In [ ]:
# 2. Create a family_members.xls file  (atleast 10 names, columns are FamilyMemberName*Relation)
# Q1> create a dataframe which contains only your brothers and sisters list.
# Q2> create a dataframe which contains only your parents list.
# Q3> create a dataframe which not contains your parents list.
# Q4> create a dataframe which not contains your brothers list.
# Q5> create a dataframe which contains either your brothers list or parents list.
# Q6> create a dataframe which contains your brothers list and parents list.

In [ ]:
# 2. Create a family_members.xls file  (atleast 10 names, columns are FamilyMemberName*Relation)

In [5]:
df_fmembers=pd.read_excel(r"C:\Users\hp\Downloads\family_names.xlsx")
df_fmembers

   S.No.   Family_members        Relation
0      1          Md. Ali          Parent
1      2      Balkis Jaha          Parent
2      3         Shahanaz          Sister
3      4       Afzal Shaw         Brother
4      5         Shakeela          Sister
5      6     Abdul Haffiz  Brother_in_law
6      7           Irfhan         Brother
7      8  Md. Karamatulla         Husbend
8      9           Shannu        Daughter
9     10             Banu        Daughter

In [ ]:
# ----> Only "Brothers and Sisters" ----> More key_values use list[] ---> isin(list)

Syntax:-

    lst=['value1','value2']
    
    a) df1=df[df.Key.isin(lst)]
       df1
            (or)
            
    b) df[df.Key.isin(lst)]

In [ ]:
# Q1> create a dataframe which contains only your brothers and sisters list.

In [6]:
lst=['Brother','Sister']

df1=df_fmembers[df_fmembers.Relation.isin(lst)]
df1

   S.No. Family_members Relation
2      3       Shahanaz   Sister
3      4     Afzal Shaw  Brother
4      5       Shakeela   Sister
6      7         Irfhan  Brother

In [ ]:
(or)

In [7]:
lst=['Brother','Sister']

df_fmembers[df_fmembers.Relation.isin(lst)]

   S.No. Family_members Relation
2      3       Shahanaz   Sister
3      4     Afzal Shaw  Brother
4      5       Shakeela   Sister
6      7         Irfhan  Brother

In [ ]:
# ------> Only ['Parent']

In [ ]:
# Q2> create a dataframe which contains only your parents list.

In [8]:
df1=df_fmembers[df_fmembers["Relation"]=="Parent"]
df1

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent

In [ ]:
(or)

In [9]:
df_fmembers[df_fmembers["Relation"]=="Parent"]

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent

In [ ]:
# ----> Not_Parent ----> Only 'One Key_value' -----> Use Symbol (!)

Syntax:-
    
    a) df1=df[df["key"]!="Key_value"]
       df1
    
              (or)
        
    b) df[df["key"]!="Key_value"]

In [ ]:
# Q3> create a dataframe which not contains your parents list.

In [10]:
Not_Parent=df_fmembers[df_fmembers["Relation"]!="Parent"]
Not_Parent

   S.No.   Family_members        Relation
2      3         Shahanaz          Sister
3      4       Afzal Shaw         Brother
4      5         Shakeela          Sister
5      6     Abdul Haffiz  Brother_in_law
6      7           Irfhan         Brother
7      8  Md. Karamatulla         Husbend
8      9           Shannu        Daughter
9     10             Banu        Daughter

In [ ]:
(or)

In [11]:
df_fmembers[df_fmembers["Relation"]!="Parent"]

   S.No.   Family_members        Relation
2      3         Shahanaz          Sister
3      4       Afzal Shaw         Brother
4      5         Shakeela          Sister
5      6     Abdul Haffiz  Brother_in_law
6      7           Irfhan         Brother
7      8  Md. Karamatulla         Husbend
8      9           Shannu        Daughter
9     10             Banu        Daughter

In [ ]:
# Q4> create a dataframe which not contains your brothers list.

In [ ]:
# --------> Not_Brothers

In [12]:
df_fmembers[df_fmembers["Relation"]!="Brother"]

   S.No.   Family_members        Relation
0      1          Md. Ali          Parent
1      2      Balkis Jaha          Parent
2      3         Shahanaz          Sister
4      5         Shakeela          Sister
5      6     Abdul Haffiz  Brother_in_law
7      8  Md. Karamatulla         Husbend
8      9           Shannu        Daughter
9     10             Banu        Daughter

In [ ]:
(or)

In [13]:
Not_Brothers=df_fmembers[df_fmembers["Relation"]!="Brother"]
Not_Brothers

   S.No.   Family_members        Relation
0      1          Md. Ali          Parent
1      2      Balkis Jaha          Parent
2      3         Shahanaz          Sister
4      5         Shakeela          Sister
5      6     Abdul Haffiz  Brother_in_law
7      8  Md. Karamatulla         Husbend
8      9           Shannu        Daughter
9     10             Banu        Daughter

In [ ]:
# Q5> create a dataframe which contains either your brothers list or parents list.

In [ ]:
# ----> 'Either' Brothers 'Or' Parents ----> Use Symbol (|)  

Syntax:-
    
    a) df1=df[(df["Key"]=="Key_value")|(df["Key"]=="Key_value")]
       df1
    
                       (or)
        
    b) df[(df["Key"]=="Key_value")|(df["Key"]=="Key_value")]

In [14]:
Or_Condition=df_fmembers[(df_fmembers["Relation"]=="Brother")|(df_fmembers["Relation"]=="Parent")]
Or_Condition

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent
3      4     Afzal Shaw  Brother
6      7         Irfhan  Brother

In [ ]:
(or)

In [15]:
df_fmembers[(df_fmembers["Relation"]=="Brother")|(df_fmembers["Relation"]=="Parent")]

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent
3      4     Afzal Shaw  Brother
6      7         Irfhan  Brother

In [ ]:
# Q6> create a dataframe which contains your brothers list and parents list.

In [ ]:
# ----> Brothers 'and' Parents ----> Two 'Key_values'   Use isin(lst)

In [16]:
lst=['Brother','Parent']

df_BP=df_fmembers[df_fmembers.Relation.isin(lst)]
df_BP

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent
3      4     Afzal Shaw  Brother
6      7         Irfhan  Brother

In [ ]:
(or)

In [17]:
lst=['Brother','Parent']

df_fmembers[df_fmembers.Relation.isin(lst)]

   S.No. Family_members Relation
0      1        Md. Ali   Parent
1      2    Balkis Jaha   Parent
3      4     Afzal Shaw  Brother
6      7         Irfhan  Brother

In [ ]:
# 3. Create a Vegfood_items.xlsx file  (atleast 10 names, columns are VegFoodName*Taste)
# Q1>create a dataframe which are  soups items
# Q2>create a dataframe which are curry items
# Q3>create a dataframe which are fry items
# Q4>create a dataframe which contains soups and fry items
# Q5>create a dataframe which not contains soups and fry items
# Q6>create a dataframe which contains either soup or fry items

In [ ]:
# 3. Create a Vegfood_items.xlsx file  (atleast 10 names, columns are VegFoodName*Taste)

In [18]:
df_Veg=pd.read_excel(r"C:\Users\hp\Downloads\Vegfood_items.xlsx")
df_Veg

    S.No. Veg Food Names  Taste
0       1     Tomato Dal  Curry
1       2           Aalu    Fry
2       3         Tomato   Soup
3       4        Cabbage    Fry
4       5  Pudina Chatny  Spicy
5       6        Brinjal  Curry
6       7  Lady's Finger    Fry
7       8         Banana  Curry
8       9   GingerChatny  Spicy
9      10        Pongali  Sweet
10     11         Noodle   Soup
11     12     Sweet Corn   Soup

In [ ]:
# Q1>create a dataframe which are  soups items

In [ ]:
# ------> Only ['Soup']

In [19]:
df_S=df_Veg[df_Veg["Taste"]=="Soup"]
df_S

    S.No. Veg Food Names Taste
2       3         Tomato  Soup
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
(or)

In [20]:
df_Veg[df_Veg["Taste"]=="Soup"]

    S.No. Veg Food Names Taste
2       3         Tomato  Soup
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
# Q2>create a dataframe which are curry items

In [ ]:
# ------> Only ['Curry']

In [21]:
df_C=df_Veg[df_Veg["Taste"]=="Curry"]
df_C

   S.No. Veg Food Names  Taste
0      1     Tomato Dal  Curry
5      6        Brinjal  Curry
7      8         Banana  Curry

In [ ]:
(or)

In [22]:
df_Veg[df_Veg["Taste"]=="Curry"]

   S.No. Veg Food Names  Taste
0      1     Tomato Dal  Curry
5      6        Brinjal  Curry
7      8         Banana  Curry

In [ ]:
# Q3>create a dataframe which are fry items

In [23]:
# ------> Only ['Fry']

In [23]:
df_F=df_Veg[df_Veg["Taste"]=="Fry"]
df_F

   S.No. Veg Food Names Taste
1      2           Aalu   Fry
3      4        Cabbage   Fry
6      7  Lady's Finger   Fry

In [ ]:
(or)

In [24]:
df_Veg[df_Veg["Taste"]=="Fry"]

   S.No. Veg Food Names Taste
1      2           Aalu   Fry
3      4        Cabbage   Fry
6      7  Lady's Finger   Fry

In [ ]:
# Q4>create a dataframe which contains soups and fry items

In [ ]:
# ----> Soup and Fry

In [25]:
lst1=['Soup','Fry']

df_SF=df_Veg[df_Veg.Taste.isin(lst1)]
df_SF

    S.No. Veg Food Names Taste
1       2           Aalu   Fry
2       3         Tomato  Soup
3       4        Cabbage   Fry
6       7  Lady's Finger   Fry
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
(or)

In [26]:
df_Veg[df_Veg.Taste.isin(lst1)]

    S.No. Veg Food Names Taste
1       2           Aalu   Fry
2       3         Tomato  Soup
3       4        Cabbage   Fry
6       7  Lady's Finger   Fry
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
# Q5>create a dataframe which not contains soups and fry items

In [ ]:
# ----> 'Not_Soup and Fry ----> Two 'Key_values' ----> Use Symbol(~)

Syntax:-

    lst=['value1','value2']

    a) df1=df[~df.Key.isin(lst)]
       df1
             (or)
        
    b) df[~df.Key.isin(lst)]

In [27]:
lst2=["Soup","Fry"]

Not_SF=df_Veg[~df_Veg.Taste.isin(lst2)]
Not_SF

   S.No. Veg Food Names  Taste
0      1     Tomato Dal  Curry
4      5  Pudina Chatny  Spicy
5      6        Brinjal  Curry
7      8         Banana  Curry
8      9   GingerChatny  Spicy
9     10        Pongali  Sweet

In [ ]:
(or)

In [28]:
lst2=["Soup","Fry"]

df_Veg[~df_Veg.Taste.isin(lst2)]

   S.No. Veg Food Names  Taste
0      1     Tomato Dal  Curry
4      5  Pudina Chatny  Spicy
5      6        Brinjal  Curry
7      8         Banana  Curry
8      9   GingerChatny  Spicy
9     10        Pongali  Sweet

In [ ]:
# Q6>create a dataframe which contains either soup or fry items

In [ ]:
# -----> 'Either' Soup 'Or' Fry items

In [29]:
df_SF=df_Veg[(df_Veg["Taste"]=="Soup")|(df_Veg["Taste"]=="Fry")]
df_SF

    S.No. Veg Food Names Taste
1       2           Aalu   Fry
2       3         Tomato  Soup
3       4        Cabbage   Fry
6       7  Lady's Finger   Fry
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
(or)

In [30]:
df_Veg[(df_Veg["Taste"]=="Soup")|(df_Veg["Taste"]=="Fry")]

    S.No. Veg Food Names Taste
1       2           Aalu   Fry
2       3         Tomato  Soup
3       4        Cabbage   Fry
6       7  Lady's Finger   Fry
10     11         Noodle  Soup
11     12     Sweet Corn  Soup

In [ ]:
# 4. Create a NonVegfood_items.xlsx file  (atleast 10 names, columns are NonVegFoodName*Taste)
# Q1>create a dataframe which contains only chicken items
# Q2>create a dataframe which contains only mutton items
# Q3>create a dataframe which contains only Fry items
# Q4>create a dataframe which contains only Fry and chicken items
# Q5>create a dataframe which not contains Fry and chicken items
# Q6>create a dataframe which c#ontains either Fry or mutton items

In [ ]:
# 4. Create a NonVegfood_items.xlsx file  (atleast 10 names, columns are NonVegFoodName*Taste)

In [31]:
df_NVeg=pd.read_excel(r"C:\Users\hp\Downloads\NVegfood_items.xlsx")
df_NVeg

    S.No. Non Veg  Food Names    Taste
0       1      Matton Biryani   Matton
1       2       Chicken Curry  Chicken
2       3        Matton Curry   Matton
3       4                Fish      Fry
4       5       Matton Khurma   Matton
5       6          Matton Fry      Fry
6       7   Chicken lolly Pop  Chicken
7       8              Kheema   Matton
8       9     Chicken Biryani  Chicken
9      10         Chicken Fry      Fry
10     11      Chilly Chicken  Chicken
11     12              Prawns      Fry

In [ ]:
# Q1>create a dataframe which contains only chicken items

In [ ]:
# ------> Only ['Chicken']

In [32]:
df_NVeg[df_NVeg["Taste"]=="Chicken"]

    S.No. Non Veg  Food Names    Taste
1       2       Chicken Curry  Chicken
6       7   Chicken lolly Pop  Chicken
8       9     Chicken Biryani  Chicken
10     11      Chilly Chicken  Chicken

In [ ]:
# Q2>create a dataframe which contains only mutton items

In [27]:
# ------> Only ['Matton']

In [33]:
df_NVeg[df_NVeg["Taste"]=="Matton"]

   S.No. Non Veg  Food Names   Taste
0      1      Matton Biryani  Matton
2      3        Matton Curry  Matton
4      5       Matton Khurma  Matton
7      8              Kheema  Matton

In [ ]:
# Q3>create a dataframe which contains only Fry items

In [ ]:
# ------> Only ['Fry']

In [34]:
df_NVeg[df_NVeg["Taste"]=="Fry"]

    S.No. Non Veg  Food Names Taste
3       4                Fish   Fry
5       6          Matton Fry   Fry
9      10         Chicken Fry   Fry
11     12              Prawns   Fry

In [ ]:
# Q4>create a dataframe which contains only Fry and chicken items

In [ ]:
# ----> Only Fry and Chicken

In [35]:
lst3=["Fry","Chicken"]

df_NVeg[df_NVeg.Taste.isin(lst3)]

    S.No. Non Veg  Food Names    Taste
1       2       Chicken Curry  Chicken
3       4                Fish      Fry
5       6          Matton Fry      Fry
6       7   Chicken lolly Pop  Chicken
8       9     Chicken Biryani  Chicken
9      10         Chicken Fry      Fry
10     11      Chilly Chicken  Chicken
11     12              Prawns      Fry

In [ ]:
# Q5>create a dataframe which not contains Fry and chicken items

In [ ]:
# ----> 'Not' Fry and Chicken

In [36]:
lst3=["Fry","Chicken"]

df_NVeg[~df_NVeg.Taste.isin(lst3)]

   S.No. Non Veg  Food Names   Taste
0      1      Matton Biryani  Matton
2      3        Matton Curry  Matton
4      5       Matton Khurma  Matton
7      8              Kheema  Matton

In [ ]:
# Q6>create a dataframe which contains either Fry or mutton items

In [ ]:
# ----> 'Either' Fry 'or' Mutton items

In [37]:
df_NVeg[(df_NVeg["Taste"]=="Fry") | (df_NVeg["Taste"]=="Matton")]

    S.No. Non Veg  Food Names   Taste
0       1      Matton Biryani  Matton
2       3        Matton Curry  Matton
3       4                Fish     Fry
4       5       Matton Khurma  Matton
5       6          Matton Fry     Fry
7       8              Kheema  Matton
9      10         Chicken Fry     Fry
11     12              Prawns     Fry

In [ ]:
# 5. Create a month_names.xlsx file (atleast 12 names, columns are MonthName*Season)
# Q1>create a dataframe which contains only winter season months
# Q2>create a dataframe which contains only summer season months
# Q3>create a dataframe which contains only rainy season months
# Q4>create a dataframe which contains only winter and summer season months
# Q5>create a dataframe which not contains summer and rainy season months
# Q6>create a dataframe which contains either winter or rainy items

In [ ]:
# 5. Create a month_names.xlsx file (atleast 12 names, columns are MonthName*Season)

In [38]:
M_names=pd.read_excel(r"C:\Users\hp\Downloads\Month_names.xlsx")
M_names

    S.No. Month Name  Season
0       1    January  Winter
1       2   February  Winter
2       3      March  Summer
3       4      April  Summer
4       5        May  Summer
5       6       June  Summer
6       7       July   Rainy
7       8     August   Rainy
8       9  September   Rainy
9      10    October   Rainy
10     11   November  Winter
11     12   December  Winter

In [ ]:
# Q1>create a dataframe which contains only winter season months

In [ ]:
# ----> Only 'Winter Season'

In [39]:
M_names[M_names["Season"]=="Winter"]

    S.No. Month Name  Season
0       1    January  Winter
1       2   February  Winter
10     11   November  Winter
11     12   December  Winter

In [ ]:
# Q2>create a dataframe which contains only summer season months

In [ ]:
# ----> Only 'Summer Season'

In [40]:
M_names[M_names["Season"]=="Summer"]

   S.No. Month Name  Season
2      3      March  Summer
3      4      April  Summer
4      5        May  Summer
5      6       June  Summer

In [ ]:
# Q3>create a dataframe which contains only rainy season months

In [ ]:
# ----> Only 'Rainy Season'

In [41]:
M_names[M_names["Season"]=="Rainy"]

   S.No. Month Name Season
6      7       July  Rainy
7      8     August  Rainy
8      9  September  Rainy
9     10    October  Rainy

In [ ]:
# Q4>create a dataframe which contains only winter and summer season months

In [ ]:
# ----> Only Winter and Summer Season

In [42]:
lst4=["Winter","Summer"]

M_names[M_names.Season.isin(lst4)]

    S.No. Month Name  Season
0       1    January  Winter
1       2   February  Winter
2       3      March  Summer
3       4      April  Summer
4       5        May  Summer
5       6       June  Summer
10     11   November  Winter
11     12   December  Winter

In [ ]:
# Q5>create a dataframe which not contains summer and rainy season months

In [ ]:
# ----> 'Not' Summer and Rainy Season (~)

In [43]:
lst5=["Summer","Rainy"]

M_names[~M_names.Season.isin(lst5)]

    S.No. Month Name  Season
0       1    January  Winter
1       2   February  Winter
10     11   November  Winter
11     12   December  Winter

In [ ]:
# Q6>create a dataframe which contains either winter or rainy items

In [ ]:
# ----> 'Either' Winter 'Or' Rainy Season

In [44]:
M_names[(M_names["Season"]=="Winter") | (M_names["Season"]=="Rainy")]

    S.No. Month Name  Season
0       1    January  Winter
1       2   February  Winter
6       7       July   Rainy
7       8     August   Rainy
8       9  September   Rainy
9      10    October   Rainy
10     11   November  Winter
11     12   December  Winter

In [ ]:
# 6. Create a flower_names.xlsx file  (atleast 12 names, columns are FlowercolourName_in_English^FlowercolourName_in_Hindi^FlowercolourName_in_Telugu)
# Q1>create a dataframe which contains only red colour flower list
# Q2>create a dataframe which contains only white colour flower list
# Q3>create a dataframe which contains only pink colour flower list
# Q4>create a dataframe which contains only red and pink colour list
# Q5>create a dataframe which not contains red and white colour list
# Q6>create a dataframe which contains either red or pink colour list

In [ ]:
# 6. Create a flower_names.xlsx file  (atleast 12 names, columns are FlowercolourName_in_English^FlowercolourName_in_Hindi^FlowercolourName_in_Telugu)

In [50]:
Flo_names=pd.read_excel(r"C:\Users\hp\Downloads\FColour.xlsx")
Flo_names

   F_Colour Eng.Name Hin.Name Tel.Name        Flowers
0       Red      Red     Laal   Earupu           Rose
1     White    White   Safhed   Telupu          Lilly
2       Red      Red     Laal   Earupu  Asiatic lilly
3      Pink     Pink   Gulabi     Roja           Rose
4     White    White   Safhed   Telupu           Rose
5      Pink     Pink   Gulabi     Roja   Spider lilly
6       Red      Red     Laal   Earupu       Hibiscus
7     White    White   Safhed   Telupu          Tulip
8      Pink     Pink   Gulabi     Roja          Daisy
9     White    White   Safhed   Telupu       Hibiscus
10      Red      Red     Laal   Earupu          Poppy
11     Pink     Pink   Gulabi     Roja          Lotus

In [ ]:
# Q1>create a dataframe which contains only red colour flower list

In [ ]:
# ----> Only 'Red Colour Flowers'

In [51]:
Flo_names[Flo_names["F_Colour"]=="Red"]

   F_Colour Eng.Name Hin.Name Tel.Name        Flowers
0       Red      Red     Laal   Earupu           Rose
2       Red      Red     Laal   Earupu  Asiatic lilly
6       Red      Red     Laal   Earupu       Hibiscus
10      Red      Red     Laal   Earupu          Poppy

In [ ]:
# Q2>create a dataframe which contains only white colour flower list

In [ ]:
# ----> Only 'White Colour Flowers'

In [52]:
Flo_names[Flo_names["F_Colour"]=="White"]

  F_Colour Eng.Name Hin.Name Tel.Name   Flowers
1    White    White   Safhed   Telupu     Lilly
4    White    White   Safhed   Telupu      Rose
7    White    White   Safhed   Telupu     Tulip
9    White    White   Safhed   Telupu  Hibiscus

In [ ]:
# Q3>create a dataframe which contains only pink colour flower list

In [ ]:
# ----> Only 'Pink Colour Flowers'

In [54]:
Flo_names[Flo_names["F_Colour"]=="Pink"]

   F_Colour Eng.Name Hin.Name Tel.Name       Flowers
3      Pink     Pink   Gulabi     Roja          Rose
5      Pink     Pink   Gulabi     Roja  Spider lilly
8      Pink     Pink   Gulabi     Roja         Daisy
11     Pink     Pink   Gulabi     Roja         Lotus

In [ ]:
# Q4>create a dataframe which contains only red and pink colour list

In [55]:
lst6=["Red","Pink"]

Flo_names[Flo_names.F_Colour.isin(lst6)]

   F_Colour Eng.Name Hin.Name Tel.Name        Flowers
0       Red      Red     Laal   Earupu           Rose
2       Red      Red     Laal   Earupu  Asiatic lilly
3      Pink     Pink   Gulabi     Roja           Rose
5      Pink     Pink   Gulabi     Roja   Spider lilly
6       Red      Red     Laal   Earupu       Hibiscus
8      Pink     Pink   Gulabi     Roja          Daisy
10      Red      Red     Laal   Earupu          Poppy
11     Pink     Pink   Gulabi     Roja          Lotus

In [ ]:
# Q5>create a dataframe which not contains red and white colour list

In [ ]:
# ---->  'Not' Red and White Colour Flowers

In [56]:
lst7=["Red","White"]

Flo_names[~Flo_names.F_Colour.isin(lst7)]

   F_Colour Eng.Name Hin.Name Tel.Name       Flowers
3      Pink     Pink   Gulabi     Roja          Rose
5      Pink     Pink   Gulabi     Roja  Spider lilly
8      Pink     Pink   Gulabi     Roja         Daisy
11     Pink     Pink   Gulabi     Roja         Lotus

In [ ]:
# Q6>create a dataframe which contains either red or pink colour list

In [57]:
# ----> 'Either' Red 'Or' Pink Colour Flowers

In [60]:
Flo_names[(Flo_names["F_Colour"]=="Red") | (Flo_names["F_Colour"]=="Pink")]

   F_Colour Eng.Name Hin.Name Tel.Name        Flowers
0       Red      Red     Laal   Earupu           Rose
2       Red      Red     Laal   Earupu  Asiatic lilly
3      Pink     Pink   Gulabi     Roja           Rose
5      Pink     Pink   Gulabi     Roja   Spider lilly
6       Red      Red     Laal   Earupu       Hibiscus
8      Pink     Pink   Gulabi     Roja          Daisy
10      Red      Red     Laal   Earupu          Poppy
11     Pink     Pink   Gulabi     Roja          Lotus