In [1]:
# -----> Assignment(5a)_Dictionary & To Create 'DATAFRAME'

In [ ]:

# Tasks:

# 3. Create a dict with your family members(at least 10 names)?
# expected output : { "family_members" : your family member details}

# 4: Create a dict with your family members and relations(at least 10 names and relations)?
# Expected output: { "family_members" : your family member details , "relations": your relation with your family member}
# write a program to print your father name?
# write a program to print your favorite family member name?

# 5: Create a your friend names and their quality(at least 10 names)?
# Expected output: {"friend_names" : your friend names, "quality" : your friend quality}
# Example output: {"friend_names": ["ravi","shekar", "abbas","jhonny"], "quality" : ["talk active", "anger", "intelligent", "funny"]}
# write a program to print your intelligent friend name?
# write a program to print your best friend name?


# 6: Create a your favorite food names and your rating(at least 10 names)?
# Expected output: {"veg_items" : food names, "rating" : your rating}
  {"nonveg_items" : food names, "rating" : your rating}
# write a program to print your rating 1 food name?


# 7: Create a your favorite destination(cities) names and your rating(at least 10 names)?
# Expected output: {"destination" : cities name, "rating" : your rating}


# 8: Create a your favorite destination(cities) names and your rating(at least 10 names)?
# Expected output: {"destination" : cities name, "rating" : your rating}
# write a program to print your rating 3 city name?

In [ ]:
# -----> dict={key:[key_values]}

In [ ]:
#3. Create a dict with your family members(at least 10 names)?
# expected output : { "family_members" : your family member details}

In [1]:
dict={"Family_members":["Md.Ali","Balkis Jaha","Shahnaz Begum","Irfan","Afzal Shaw","Shakeela Begum","Shamshad Begum","Md.Karamatulla","Abidunnisa","Shahnaz Banu"]}
dict

{'Family_members': ['Md.Ali',
  'Balkis Jaha',
  'Shahnaz Begum',
  'Irfan',
  'Afzal Shaw',
  'Shakeela Begum',
  'Shamshad Begum',
  'Md.Karamatulla',
  'Abidunnisa',
  'Shahnaz Banu']}

In [2]:
print("My Family Member Details:",dict)

My Family Member Details: {'Family_members': ['Md.Ali', 'Balkis Jaha', 'Shahnaz Begum', 'Irfan', 'Afzal Shaw', 'Shakeela Begum', 'Shamshad Begum', 'Md.Karamatulla', 'Abidunnisa', 'Shahnaz Banu']}

In [ ]:
# ----> Dictionary to Create 'Data Frame'

Syntax:- 
    
    df=pd.DataFrame(dict)
    df

In [3]:
import pandas
import pandas as pd
df_Fmembers=pd.DataFrame(dict)
df_Fmembers

   Family_members
0          Md.Ali
1     Balkis Jaha
2   Shahnaz Begum
3           Irfan
4      Afzal Shaw
5  Shakeela Begum
6  Shamshad Begum
7  Md.Karamatulla
8      Abidunnisa
9    Shahnaz Banu

In [4]:
#4: Create a dict with your family members and relations(at least 10 names and relations)?
# Expected output: { "family_members" : your family member details , "relations": your relation with your family member}
# write a program to print your father name?
# write a program to print your favorite family member name?

In [4]:
dict_re={"Family_members":["Md.Ali","Balkis Jaha","Shahnaz Begum","Irfan","Afzal Shaw","Shakeela Begum","Shamshad Begum","Md.Karamatulla","Abidunnisa","Shahnaz Banu"], "Relations":["Father","Mother","Elder Sister","Elder Brother","Elder Brother","Younger Sister","Me","Husband","Elder Daugher","Younger Daughter"]}
dict_re

{'Family_members': ['Md.Ali',
  'Balkis Jaha',
  'Shahnaz Begum',
  'Irfan',
  'Afzal Shaw',
  'Shakeela Begum',
  'Shamshad Begum',
  'Md.Karamatulla',
  'Abidunnisa',
  'Shahnaz Banu'],
 'Relations': ['Father',
  'Mother',
  'Elder Sister',
  'Elder Brother',
  'Elder Brother',
  'Younger Sister',
  'Me',
  'Husband',
  'Elder Daugher',
  'Younger Daughter']}

In [5]:
print("My Family Members Details:",dict_re)

My Family Members Details: {'Family_members': ['Md.Ali', 'Balkis Jaha', 'Shahnaz Begum', 'Irfan', 'Afzal Shaw', 'Shakeela Begum', 'Shamshad Begum', 'Md.Karamatulla', 'Abidunnisa', 'Shahnaz Banu'], 'Relations': ['Father', 'Mother', 'Elder Sister', 'Elder Brother', 'Elder Brother', 'Younger Sister', 'Me', 'Husband', 'Elder Daugher', 'Younger Daughter']}

In [ ]:
# -----> Dictionary to Create 'Data Frame'

In [6]:
df_fmembers=pd.DataFrame(dict_re)
df_fmembers

   Family_members         Relations
0          Md.Ali            Father
1     Balkis Jaha            Mother
2   Shahnaz Begum      Elder Sister
3           Irfan     Elder Brother
4      Afzal Shaw     Elder Brother
5  Shakeela Begum    Younger Sister
6  Shamshad Begum                Me
7  Md.Karamatulla           Husband
8      Abidunnisa     Elder Daugher
9    Shahnaz Banu  Younger Daughter

In [ ]:
# write a program to print your father name?

In [7]:
print("My Father Name is:",dict_re["Family_members"][0])

My Father Name is: Md.Ali

In [ ]:
# write a program to print your favorite family member name?

In [8]:
print("MY Favorite Family Member Name is:",dict_re["Family_members"][0])

MY Favorite Family Member Name is: Md.Ali

In [ ]:
#5: Create a your friend names and their quality(at least 10 names)?
# Expected output: {"friend_names" : your friend names, "quality" : your friend quality}
# Example output: {"friend_names": ["ravi","shekar", "abbas","jhonny"], "quality" : ["talk active", "anger", "intelligent", "funny"]}
# write a program to print your intelligent friend name?
# write a program to print your best friend name?

In [ ]:
#5: Create a your friend names and their quality(at least 10 names)?

In [9]:
dict_fn={"Friend_names": ["Ravi","Shekar", "Abbas","Aliya","Perveen","Khamurunnisa","Salma","Radhika","Sridevi","Jarina"], "Quality" : ["Talk Active", "Anger", "Good Singer", "Funny", "Honesty", "Intelligent", "Innocent", "Claver", "Hard Working", "Help full"]}
dict_fn

{'Friend_names': ['Ravi',
  'Shekar',
  'Abbas',
  'Aliya',
  'Perveen',
  'Khamurunnisa',
  'Salma',
  'Radhika',
  'Sridevi',
  'Jarina'],
 'Quality': ['Talk Active',
  'Anger',
  'Good Singer',
  'Funny',
  'Honesty',
  'Intelligent',
  'Innocent',
  'Claver',
  'Hard Working',
  'Help full']}

In [ ]:
# --------> Dictionary to Create 'Data Frame'

In [10]:
df_Quality=pd.DataFrame(dict_fn)
df_Quality

   Friend_names       Quality
0          Ravi   Talk Active
1        Shekar         Anger
2         Abbas   Good Singer
3         Aliya         Funny
4       Perveen       Honesty
5  Khamurunnisa   Intelligent
6         Salma      Innocent
7       Radhika        Claver
8       Sridevi  Hard Working
9        Jarina     Help full

In [ ]:
# write a program to print your intelligent friend name?

In [11]:
print ("My Intelligent Friend Name is :",dict_fn["Friend_names"][5])

My Intelligent Friend Name is : Khamurunnisa

In [ ]:
# write a program to print your best friend name?

In [12]:
print("My Best Friend Name is :",dict_fn["Friend_names"][3])

My Best Friend Name is : Aliya

In [ ]:
#6: Create a your favorite food names and your rating(at least 10 names)?
# Expected output: {"veg_items" : food names, "rating" : your rating}
# {"nonveg_items" : food names, "rating" : your rating}
# write a program to print your rating 1 food name?

In [13]:
dict_vr={"Veg_items" : ["Potato fry","Tomato dal","Pudina Chatny","Brinjal dal","Lady's finger fry","Potato Tomato Curry","Brinjal Curry","Ridge Guard Curry","Sambar","Snake guard Curry"],"Rating":[2,1,5,7,3,8,4,9,6,10]}
dict_vr

{'Veg_items': ['Potato fry',
  'Tomato dal',
  'Pudina Chatny',
  'Brinjal dal',
  "Lady's finger fry",
  'Potato Tomato Curry',
  'Brinjal Curry',
  'Ridge Guard Curry',
  'Sambar',
  'Snake guard Curry'],
 'Rating': [2, 1, 5, 7, 3, 8, 4, 9, 6, 10]}

In [ ]:
# --------> Dictionary to Create 'Data FFrame'

In [14]:
df_Veg=pd.DataFrame(dict_vr)
df_Veg

             Veg_items  Rating
0           Potato fry       2
1           Tomato dal       1
2        Pudina Chatny       5
3          Brinjal dal       7
4    Lady's finger fry       3
5  Potato Tomato Curry       8
6        Brinjal Curry       4
7    Ridge Guard Curry       9
8               Sambar       6
9    Snake guard Curry      10

In [15]:
dict_nveg={"NV_items" :["Matton Curry","Chicken Curry","Matton Khurma","Matton Biryani","Chicken Biryani","Chicken fry","Matton fry","Fish  Curry","Fish fry","Prawns fry"],"Rating":[4,10,3,1,2,8,5,7,6,9]}
dict_nveg

{'NV_items': ['Matton Curry',
  'Chicken Curry',
  'Matton Khurma',
  'Matton Biryani',
  'Chicken Biryani',
  'Chicken fry',
  'Matton fry',
  'Fish  Curry',
  'Fish fry',
  'Prawns fry'],
 'Rating': [4, 10, 3, 1, 2, 8, 5, 7, 6, 9]}

In [ ]:
# --------> Dictionary to Create 'Data Frame'

In [16]:
df_NV=pd.DataFrame(dict_nveg)
df_NV

          NV_items  Rating
0     Matton Curry       4
1    Chicken Curry      10
2    Matton Khurma       3
3   Matton Biryani       1
4  Chicken Biryani       2
5      Chicken fry       8
6       Matton fry       5
7      Fish  Curry       7
8         Fish fry       6
9       Prawns fry       9

In [ ]:
# write a program to print your rating 1 food name?

In [17]:
print("Rating 1 Food Name is : ",dict_vr["Veg_items"][1])

Rating 1 Food Name is :  Tomato dal

In [18]:
print("Rating 1 Food Name is : ",dict_nveg["NV_items"][3])

Rating 1 Food Name is :  Matton Biryani

In [19]:
print("Rating 1 Food Names are : ",dict_vr["Veg_items"][1], dict_nveg["NV_items"][3])

Rating 1 Food Names are :  Tomato dal Matton Biryani

In [ ]:
# 7: Create a your favorite destination(cities) names and your rating(at least 10 names)?
Expected output: {"destination" : cities name, "rating" : your rating}

In [20]:
dict_destination={"City_names" :["Delhi","Mumbai","Kolkata","Chennai","Lacknow","Hyderabad","Varanasi","Bangalure","Ahmedabad","Surat"],"My Rating":[4,6,3,5,8,2,7,1,9,10]}
dict_destination

{'City_names': ['Delhi',
  'Mumbai',
  'Kolkata',
  'Chennai',
  'Lacknow',
  'Hyderabad',
  'Varanasi',
  'Bangalure',
  'Ahmedabad',
  'Surat'],
 'My Rating': [4, 6, 3, 5, 8, 2, 7, 1, 9, 10]}

In [21]:
print ("My Favorite Destination City Name is:",dict_destination["City_names"][7])

My Favorite Destination City Name is: Bangalure

In [ ]:
# ----> Dictionary to Create 'Data Frame'

In [22]:
df_City=pd.DataFrame(dict_destination)
df_City

  City_names  My Rating
0      Delhi          4
1     Mumbai          6
2    Kolkata          3
3    Chennai          5
4    Lacknow          8
5  Hyderabad          2
6   Varanasi          7
7  Bangalure          1
8  Ahmedabad          9
9      Surat         10

In [ ]:
# 8: Create a your favorite destination(cities) names and your rating(at least 10 names)?
# Expected output: {"destination" : cities name, "rating" : your rating}
# write a program to print your rating 3 city name?

In [23]:
# write a program to print your rating 3 city name?

print("My Rating 3 City Name is:",dict_destination["City_names"][2])

My Rating 3 City Name is: Kolkata