In [ ]:
# ----> Assignment(11) ----> Python_Append_Practice

In [ ]:
# Task: create a program
# Q1>Create and import file
# 1. Create boys Boysfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality) ,
# 2. Create girls Girlsfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality),
# 3. Append two dataframes and print data.


# Q3>Create and import file
# 1. Create a father side fatherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)
# 2. Create a mother side montherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)
# 3. Append two dataframes and print data.

# Q4>Create and import file
# 1. Create your sister names  Sisters.xls file and import file in spyder  (atleast 5 names, columns are SisterName*Relation)
# 2. Create your brother names Brothers.xls file and import file in spyder  (atleast 5 names, columns are BrotherName*Relation)
# 3. Append two dataframes and print data.


# Q5>Create and import file
# 1. Create a Dal related  dal_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)
# 2. Create a vegitable related  vegitable_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)
# 3. Append two dataframes and print data.

# Q6>Create and import file
# 1. Create a soups related  soups_items.xlsx file and import file in spyder (atleast 5 names, columns are soups*Taste)
# 2. Create a fry related  fry_items.xlsx file and import file in spyder (atleast 5 names, columns are fry*Taste)
# 3. Append two dataframes and print data.

# Q7>Create and import file
# 1. Create a Chicken related chicken_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)
# 2. Create a mutton related mutton_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)
# 3. Append two dataframes and print data.


# Q8>Create and import file
# 1. Create a winter season  winterseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
# 2. Create a summer season  summerseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
# 3. Create a rainy season  rainyseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
# 4. Append all dataframes and print data.


# Q9>Create and import file
# 1. Create a red colour flowers redflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 2. Create a white colour flowers whiteflowers_names.xlsx file  and import file in spyder  (atleast 3 names, columns are FlowerName*color)
# 3. Create a pink colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 4. Create a yellow colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 5. Append all dataframes and print data.

In [ ]:
# Task: create a program
# Q1>Create and import file
# 1. Create boys Boysfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality) ,
# 2. Create girls Girlsfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality),
# 3. Append two dataframes and print data.

In [ ]:
# 1. Create boys Boysfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality) ,

In [1]:
import pandas
import pandas as pd
df_b=pd.read_excel(r"C:\Users\hp\Downloads\Boysfriends_Names.xlsx")
df_b

   S.No. Boys Friends Name      Quality
0      1             Srinu  Intelligent
1      2             Shyam         Good
2      3           Rehaman  Intelligent
3      4            Munwar     Innocent
4      5              Rafi       Clever
5      6            Prasad        Funny
6      7              Kali         Good
7      8            Rajesh       Clever
8      9             Eswar      Honesty
9     10             Afzal     Innocent

In [ ]:
# 2. Create girls Girlsfriend_names.xls file and import file in spyder (atleast 10 names, columns are FriendName,Quality),

In [2]:
df_g=pd.read_excel(r"C:\Users\hp\Downloads\Girlsfriends_Names.xlsx")
df_g

   S.No. Girls Friends Names      Quality
0      1              Hanima  Intelligent
1      2               Munni         Good
2      3             Parveen       Clever
3      4            Nagamani     Innocent
4      5              Pushpa         Good
5      6            Shafeeka        Funny
6      7             Sultana       Active
7      8              Devika  Intelligent
8      9             Radhika       Clever
9     10                Jaya     Innocent

In [ ]:
1) axis=0 ---> To Display data ["One by One"]

2) axis=1 ---> To Display data ["Side by Side"]

# --------> Append ------> (Two_Tables Join)

Syntax:-

    Ap=pd.concat([df1,df2],axis=0)
    Ap
    
    Ap1=pd.concat([df1,df2],axis=1)
    Ap1
    
ex:-
    
    Ap=pd.concat([df_b,df_g],axis=0)
    Ap

    Ap1=pd.concat([df_b,df_g],axis=1)
    Ap
    
# --------> Append ------> (Three_Tables Join)

Syntax:-

In [ ]:
# -------> Append ------> [Join Two_Tables]

In [ ]:
1) axis=0 ---> To Display data ["One by One"]

In [ ]:
# 3. Append two dataframes and print data.

In [3]:
Append=pd.concat([df_b,df_g],axis=0)
Append

   S.No. Boys Friends Name      Quality Girls Friends Names
0      1             Srinu  Intelligent                 NaN
1      2             Shyam         Good                 NaN
2      3           Rehaman  Intelligent                 NaN
3      4            Munwar     Innocent                 NaN
4      5              Rafi       Clever                 NaN
5      6            Prasad        Funny                 NaN
6      7              Kali         Good                 NaN
7      8            Rajesh       Clever                 NaN
8      9             Eswar      Honesty                 NaN
9     10             Afzal     Innocent                 NaN
0      1               NaN  Intelligent              Hanima
1      2               NaN         Good               Munni
2      3               NaN       Clever             Parveen
3      4               NaN     Innocent            Nagamani
4      5               NaN         Good              Pushpa
5      6               NaN        Funny            Shafeeka
6      7               NaN       Active             Sultana
7      8               NaN  Intelligent              Devika
8      9               NaN       Clever             Radhika
9     10               NaN     Innocent                Jaya

In [ ]:
2) axis=1 ---> To Display data ["Side by Side"]

In [4]:
Append1=pd.concat([df_b,df_g],axis=1)
Append1

,S.No.,Boys Friends Name,Quality,S.No.,Girls Friends Names,Quality
0,1,Srinu,Intelligent,1,Hanima,Intelligent
1,2,Shyam,Good,2,Munni,Good
2,3,Rehaman,Intelligent,3,Parveen,Clever
3,4,Munwar,Innocent,4,Nagamani,Innocent
4,5,Rafi,Clever,5,Pushpa,Good
5,6,Prasad,Funny,6,Shafeeka,Funny
6,7,Kali,Good,7,Sultana,Active
7,8,Rajesh,Clever,8,Devika,Intelligent
8,9,Eswar,Honesty,9,Radhika,Clever
9,10,Afzal,Innocent,10,Jaya,Innocent

In [ ]:
# Q3>Create and import file
# 1. Create a father side fatherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)
# 2. Create a mother side montherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)
# 3. Append two dataframes and print data.

In [ ]:
# 1. Create a father side fatherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)

In [5]:
df_Fm=pd.read_excel(r"C:\Users\hp\Downloads\Ffamily_members.xlsx")
df_Fm

   S.No. F.Family Members      Relation
0      1       Jani Saheb  Grand_father
1      2         Jainabbi  Grand_mother
2      3     Perveen Jaha         Aunty
3      4       Nawab Jani         Uncle
4      5   Mohammed Saheb     Chinnanna
5      6         Md.Samad     Chinnanna

In [ ]:
# 2. Create a mother side montherfamily_members.xls file and import file in spyder  (atleast 5 names, columns are FamilyMemberName*Relation)

In [6]:
df_Mm=pd.read_excel(r"C:\Users\hp\Downloads\Mfamily_members.xlsx")
df_Mm

   S.No. M.Family Members      Relation
0      1    Khasim Sharif  Grand_father
1      2     Rabiya Begum  Grand_mother
2      3      Naseem Jaha     peddhamma
3      4      Balkis Jaha     My Mother
4      5     Perveen Jaha         Pinni
5      6    Humayun Basha       Mamayya

In [ ]:
# 3. Append two dataframes and print data.

In [ ]:
axis=0

In [7]:
Ap_FM=pd.concat([df_Fm,df_Mm],axis=0)
Ap_FM

   S.No. F.Family Members      Relation M.Family Members
0      1       Jani Saheb  Grand_father              NaN
1      2         Jainabbi  Grand_mother              NaN
2      3     Perveen Jaha         Aunty              NaN
3      4       Nawab Jani         Uncle              NaN
4      5   Mohammed Saheb     Chinnanna              NaN
5      6         Md.Samad     Chinnanna              NaN
0      1              NaN  Grand_father    Khasim Sharif
1      2              NaN  Grand_mother     Rabiya Begum
2      3              NaN     peddhamma      Naseem Jaha
3      4              NaN     My Mother      Balkis Jaha
4      5              NaN         Pinni     Perveen Jaha
5      6              NaN       Mamayya    Humayun Basha

In [ ]:
axis=1

In [8]:
Ap_FM1=pd.concat([df_Fm,df_Mm],axis=1)
Ap_FM1

   S.No. F.Family Members      Relation  S.No. M.Family Members      Relation
0      1       Jani Saheb  Grand_father      1    Khasim Sharif  Grand_father
1      2         Jainabbi  Grand_mother      2     Rabiya Begum  Grand_mother
2      3     Perveen Jaha         Aunty      3      Naseem Jaha     peddhamma
3      4       Nawab Jani         Uncle      4      Balkis Jaha     My Mother
4      5   Mohammed Saheb     Chinnanna      5     Perveen Jaha         Pinni
5      6         Md.Samad     Chinnanna      6    Humayun Basha       Mamayya

In [ ]:
# Q4>Create and import file
# 1. Create your sister names  Sisters.xls file and import file in spyder  (atleast 5 names, columns are SisterName*Relation)
# 2. Create your brother names Brothers.xls file and import file in spyder  (atleast 5 names, columns are BrotherName*Relation)
# 3. Append two dataframes and print data.

In [ ]:
# 1. Create your sister names  Sisters.xls file and import file in spyder  (atleast 5 names, columns are SisterName*Relation)

In [9]:
df_Sis=pd.read_excel(r"C:\Users\hp\Downloads\Sisters_Names.xlsx")
df_Sis

   S.No. Sis_Names        Relation
0      1     Abida    Elder_Sister
1      2   Gowsiya    Elder_Sister
2      3  Shahanaz    Elder_Sister
3      4  Shakeela  Younger_Sister
4      5   Sultana    Elder_Sister

In [ ]:
# 2. Create your brother names Brothers.xls file and import file in spyder  (atleast 5 names, columns are BrotherName*Relation)

In [10]:
df_Bro=pd.read_excel(r"C:\Users\hp\Downloads\Brothers_Names.xlsx")
df_Bro

   S.No.   Bro_Names         Relation
0      1      Shammi    Elder_Brother
1      2      Shamun    Elder_Brother
2      3     Shakeel  Younger_Brother
3      4     Khaleel    Elder_Brother
4      5  Afzal Shaw    Elder_Brother

In [ ]:
axis=0

In [ ]:
# 3. Append two dataframes and print data.

In [11]:
Ap_SB=pd.concat([df_Sis,df_Bro],axis=0)
Ap_SB

   S.No. Sis_Names         Relation   Bro_Names
0      1     Abida     Elder_Sister         NaN
1      2   Gowsiya     Elder_Sister         NaN
2      3  Shahanaz     Elder_Sister         NaN
3      4  Shakeela   Younger_Sister         NaN
4      5   Sultana     Elder_Sister         NaN
0      1       NaN    Elder_Brother      Shammi
1      2       NaN    Elder_Brother      Shamun
2      3       NaN  Younger_Brother     Shakeel
3      4       NaN    Elder_Brother     Khaleel
4      5       NaN    Elder_Brother  Afzal Shaw

In [ ]:
axis=1

In [12]:
Ap_SB1=pd.concat([df_Sis,df_Bro],axis=1)
Ap_SB1

   S.No. Sis_Names        Relation  S.No.   Bro_Names         Relation
0      1     Abida    Elder_Sister      1      Shammi    Elder_Brother
1      2   Gowsiya    Elder_Sister      2      Shamun    Elder_Brother
2      3  Shahanaz    Elder_Sister      3     Shakeel  Younger_Brother
3      4  Shakeela  Younger_Sister      4     Khaleel    Elder_Brother
4      5   Sultana    Elder_Sister      5  Afzal Shaw    Elder_Brother

In [ ]:
# Q5>Create and import file
# 1. Create a Dal related  dal_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)
# 2. Create a vegitable related  vegitable_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)
# 3. Append two dataframes and print data.

In [ ]:
# 1. Create a Dal related  dal_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)

In [13]:
df_Dal=pd.read_excel(r"C:\Users\hp\Downloads\dal_items.xlsx")
df_Dal

   S.No. Veg.Food_Names    Taste
0      1     Tomato dal   Supper
1      2        Sambaar     Good
2      3    Brinjal dal  Average
3      4    Spinach dal     Good
4      5    Cabbage dal  Average

In [ ]:
# 2. Create a vegitable related  vegitable_items.xlsx file and import file in spyder (atleast 5 names, columns are VegFoodName*Taste)

In [14]:
df_Veg=pd.read_excel(r"C:\Users\hp\Downloads\VegFood_ Names.xlsx")
df_Veg

   S.No.     Veg.Food Names   Taste
0      1         Potato Fry   Spicy
1      2   Snake gard Curry    Good
2      3      Brinjal Curry  Supper
3      4  Ladies finger Fry   Yammy
4      5       Tomato Curry    Good

In [ ]:
# 3. Append two dataframes and print data.

In [ ]:
axis=0

In [15]:
Ap_DV=pd.concat([df_Dal,df_Veg],axis=0)
Ap_DV

   S.No. Veg.Food_Names    Taste     Veg.Food Names
0      1     Tomato dal   Supper                NaN
1      2        Sambaar     Good                NaN
2      3    Brinjal dal  Average                NaN
3      4    Spinach dal     Good                NaN
4      5    Cabbage dal  Average                NaN
0      1            NaN    Spicy         Potato Fry
1      2            NaN     Good   Snake gard Curry
2      3            NaN   Supper      Brinjal Curry
3      4            NaN    Yammy  Ladies finger Fry
4      5            NaN     Good       Tomato Curry

In [ ]:
axis=1

In [16]:
Ap_DV1=pd.concat([df_Dal,df_Veg],axis=1)
Ap_DV1

   S.No. Veg.Food_Names    Taste  S.No.     Veg.Food Names   Taste
0      1     Tomato dal   Supper      1         Potato Fry   Spicy
1      2        Sambaar     Good      2   Snake gard Curry    Good
2      3    Brinjal dal  Average      3      Brinjal Curry  Supper
3      4    Spinach dal     Good      4  Ladies finger Fry   Yammy
4      5    Cabbage dal  Average      5       Tomato Curry    Good

In [ ]:
# Q6>Create and import file
# 1. Create a soups related  soups_items.xlsx file and import file in spyder (atleast 5 names, columns are soups*Taste)
# 2. Create a fry related  fry_items.xlsx file and import file in spyder (atleast 5 names, columns are fry*Taste)
# 3. Append two dataframes and print data.

In [ ]:
# 1. Create a soups related  soups_items.xlsx file and import file in spyder (atleast 5 names, columns are soups*Taste)

In [17]:
df_Soups=pd.read_excel(r"C:\Users\hp\Downloads\Soup_items.xlsx")
df_Soups

   S.No.            Soups   Taste
0      1      Tomato Soup   Yammy
1      2     Chicken Soup  Supper
2      3      Matton Soup   Spicy
3      4      Noodle Soup     Hot
4      5  Sweet Corn Soup   Spicy

In [ ]:
# 2. Create a fry related  fry_items.xlsx file and import file in spyder (atleast 5 names, columns are fry*Taste)

In [18]:
df_Fry=pd.read_excel(r"C:\Users\hp\Downloads\Fry_items.xlsx")
df_Fry

   S.No.         Fry _items   Taste
0      1         Potato Fry  Supper
1      2         Matton Fry   Spicy
2      3        Chicken Fry     Hot
3      4  Ladies Finger Fry   Yammy
4      5           Fish Fry   Spicy

In [ ]:
# 3. Append two dataframes and print data.

In [ ]:
axis=0

In [19]:
Ap_SF=pd.concat([df_Soups,df_Fry],axis=0)
Ap_SF

   S.No.            Soups   Taste         Fry _items
0      1      Tomato Soup   Yammy                NaN
1      2     Chicken Soup  Supper                NaN
2      3      Matton Soup   Spicy                NaN
3      4      Noodle Soup     Hot                NaN
4      5  Sweet Corn Soup   Spicy                NaN
0      1              NaN  Supper         Potato Fry
1      2              NaN   Spicy         Matton Fry
2      3              NaN     Hot        Chicken Fry
3      4              NaN   Yammy  Ladies Finger Fry
4      5              NaN   Spicy           Fish Fry

In [ ]:
axis=1

In [20]:
Ap_SF1=pd.concat([df_Soups,df_Fry],axis=1)
Ap_SF1

   S.No.            Soups   Taste  S.No.         Fry _items   Taste
0      1      Tomato Soup   Yammy      1         Potato Fry  Supper
1      2     Chicken Soup  Supper      2         Matton Fry   Spicy
2      3      Matton Soup   Spicy      3        Chicken Fry     Hot
3      4      Noodle Soup     Hot      4  Ladies Finger Fry   Yammy
4      5  Sweet Corn Soup   Spicy      5           Fish Fry   Spicy

In [ ]:
# Q7>Create and import file
# 1. Create a Chicken related chicken_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)
# 2. Create a mutton related mutton_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)
# 3. Append two dataframes and print data

In [ ]:
# 1. Create a Chicken related chicken_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)

In [21]:
df_Chicken=pd.read_excel(r"C:\Users\hp\Downloads\Chicken_items.xlsx")
df_Chicken

   S.No. Chicken Food Names    Taste
0      1    Chicken Biryani   Supper
1      2     Chicken Khurma      Hot
2      3       Chicken  Fry    Spicy
3      4     Chicken Chilly     Good
4      5       Chicken Soup  Average

In [ ]:
# 2. Create a mutton related mutton_items.xlsx file and import file in spyder (atleast 5 names, columns are NonVegFoodName*Taste)

In [22]:
df_Matton=pd.read_excel(r"C:\Users\hp\Downloads\Matton_items.xlsx")
df_Matton

   S.No.    Matton Food Names   Taste
0      1       Matton Biryani  Supper
1      2        Matton Khurma   Spicy
2      3           Matton Fry  Crispy
3      4  Matton Masala Curry   Spicy
4      5          Matton Paya     Hot

In [ ]:
# 3. Append two dataframes and print data

In [ ]:
axis=0

In [23]:
Ap_CM=pd.concat([df_Chicken,df_Matton],axis=0)
Ap_CM

   S.No. Chicken Food Names    Taste    Matton Food Names
0      1    Chicken Biryani   Supper                  NaN
1      2     Chicken Khurma      Hot                  NaN
2      3       Chicken  Fry    Spicy                  NaN
3      4     Chicken Chilly     Good                  NaN
4      5       Chicken Soup  Average                  NaN
0      1                NaN   Supper       Matton Biryani
1      2                NaN    Spicy        Matton Khurma
2      3                NaN   Crispy           Matton Fry
3      4                NaN    Spicy  Matton Masala Curry
4      5                NaN      Hot          Matton Paya

In [ ]:
axis=1

In [24]:
Ap_CM1=pd.concat([df_Chicken,df_Matton],axis=1)
Ap_CM1

   S.No. Chicken Food Names    Taste  S.No.    Matton Food Names   Taste
0      1    Chicken Biryani   Supper      1       Matton Biryani  Supper
1      2     Chicken Khurma      Hot      2        Matton Khurma   Spicy
2      3       Chicken  Fry    Spicy      3           Matton Fry  Crispy
3      4     Chicken Chilly     Good      4  Matton Masala Curry   Spicy
4      5       Chicken Soup  Average      5          Matton Paya     Hot

In [ ]:
# -------> Append ------> [Join Three_Tables]

In [ ]:
# Q8>Create and import file
# 1. Create a winter season  winterseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
# 2. Create a summer season  summerseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
"C:\Users\hp\Begum_Excel_Sheets\Matton_items.xlsx"# 3. Create a rainy season  rainyseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)
# 4. Append all dataframes and print data.

In [ ]:
# 1. Create a winter season  winterseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)

In [25]:
df_Winter=pd.read_excel(r"C:\Users\hp\Downloads\Winter_season.xlsx")
df_Winter

   S.No. Month Names  Season
0      1    November  Winter
1      2    December  Winter
2      3     January  Winter

In [ ]:
# 2. Create a summer season  summerseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)

In [26]:
df_Summer=pd.read_excel(r"C:\Users\hp\Downloads\Summer_Season.xlsx")
df_Summer

   S.No. Month Names  Season
0      1       March  Summer
1      2       April  Summer
2      3         May  Summer

In [ ]:
# 3. Create a rainy season  rainyseason_names.xlsx file and import file in spyder  (atleast 2 names, columns are MonthName*Season)

In [27]:
df_Rainy=pd.read_excel(r"C:\Users\hp\Downloads\Rainy_Season.xlsx")
df_Rainy

   S.No. Month Names Season
0      1        July  Rainy
1      2      August  Rainy
2      3   September  Rainy

In [ ]:
# -------> Append ------> [Join 'Three_Tables']

In [ ]:
# 4. Append all dataframes and print data.

In [ ]:
axis=0

In [28]:
Ap_Seasons=pd.concat([df_Winter,df_Summer,df_Rainy],axis=0)
Ap_Seasons

   S.No. Month Names  Season
0      1    November  Winter
1      2    December  Winter
2      3     January  Winter
0      1       March  Summer
1      2       April  Summer
2      3         May  Summer
0      1        July   Rainy
1      2      August   Rainy
2      3   September   Rainy

In [ ]:
axis=1

In [29]:
Ap_Seasons1=pd.concat([df_Winter,df_Summer,df_Rainy],axis=1)
Ap_Seasons1

,S.No.,Month Names,Season,S.No.,Month Names,Season,S.No.,Month Names,Season
0,1,November,Winter,1,March,Summer,1,July,Rainy
1,2,December,Winter,2,April,Summer,2,August,Rainy
2,3,January,Winter,3,May,Summer,3,September,Rainy

In [ ]:
# -------> Append ------> [Join 'Four_Tables']

In [ ]:
# Q9>Create and i#mport file
# 1. Create a red colour flowers redflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 2. Create a white colour flowers whiteflowers_names.xlsx file  and import file in spyder  (atleast 3 names, columns are FlowerName*color)
# 3. Create a pink colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 4. Create a yellow colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)
# 5. Append all dataframes and print data.

In [ ]:
# 1. Create a red colour flowers redflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)

In [31]:
df_Red=pd.read_excel(r"C:\Users\hp\Downloads\Redflowers_Names.xlsx")
df_Red

   S.No. Flower Names Colour
0      1         Rose    Red
1      2        Poppy    Red
2      3     Marigold    Red
3      4      Hibicus    Red

In [ ]:
# 2. Create a white colour flowers whiteflowers_names.xlsx file  and import file in spyder  (atleast 3 names, columns are FlowerName*color)

In [32]:
df_White=pd.read_excel(r"C:\Users\hp\Downloads\Whiteflowers_Names.xlsx")
df_White

   S.No. Flower  Names Colour
0      1          Lily  White
1      2         Daisy  White
2      3         Roses  White
3      4         Peony  White

In [ ]:
# 3. Create a pink colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)

In [33]:
df_Pink=pd.read_excel(r"C:\Users\hp\Downloads\Pinkflowers_Names.xlsx")
df_Pink

   S.No. Flower Names Colour
0      1         Rose   Pink
1      2       Tulips   Pink
2      3        Lotus   Pink
3      4  Spider Lily   Pink

In [ ]:
# 4. Create a yellow colour flowers whiteflowers_names.xlsx file and import file in spyder   (atleast 3 names, columns are FlowerName*color)

In [34]:
df_Yellow=pd.read_excel(r"C:\Users\hp\Downloads\Yellowflowers_Names.xlsx")
df_Yellow

   S.No.    Flower Names  Colour
0      1        Hibiscus  Yellow
1      2       Bar Berry  Yellow
2      3    Butter Daisy  Yellow
3      4  Winter Jasmine  Yellow

In [ ]:
# -------> Append ------> [Join 'Four_Tables']

In [ ]:
# 5. Append all dataframes and print data.

In [ ]:
axis=0

In [35]:
Ap_FColour=pd.concat([df_Red,df_White,df_Pink,df_Yellow],axis=0)
Ap_FColour

   S.No.    Flower Names  Colour Flower  Names
0      1            Rose     Red           NaN
1      2           Poppy     Red           NaN
2      3        Marigold     Red           NaN
3      4         Hibicus     Red           NaN
0      1             NaN   White          Lily
1      2             NaN   White         Daisy
2      3             NaN   White         Roses
3      4             NaN   White         Peony
0      1            Rose    Pink           NaN
1      2          Tulips    Pink           NaN
2      3           Lotus    Pink           NaN
3      4     Spider Lily    Pink           NaN
0      1        Hibiscus  Yellow           NaN
1      2       Bar Berry  Yellow           NaN
2      3    Butter Daisy  Yellow           NaN
3      4  Winter Jasmine  Yellow           NaN

In [ ]:
axis=1

In [36]:
Ap_FColour1=pd.concat([df_Red,df_White,df_Pink,df_Yellow],axis=1)
Ap_FColour1

,S.No.,Flower Names,Colour,S.No.,Flower Names,Colour,S.No.,Flower Names,Colour,S.No.,Flower Names,Colour
0,1,Rose,Red,1,Lily,White,1,Rose,Pink,1,Hibiscus,Yellow
1,2,Poppy,Red,2,Daisy,White,2,Tulips,Pink,2,Bar Berry,Yellow
2,3,Marigold,Red,3,Roses,White,3,Lotus,Pink,3,Butter Daisy,Yellow
3,4,Hibicus,Red,4,Peony,White,4,Spider Lily,Pink,4,Winter Jasmine,Yellow